; Listing generated by Microsoft (R) Optimizing Compiler Version 19.37.32822.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_06BPMFKDCM@topBar@			; `string'
PUBLIC	??_C@_08ENPEKDLI@addEntry@			; `string'
PUBLIC	??_C@_0L@EDDKEFDJ@contentBar@			; `string'
PUBLIC	??_C@_09LBJLMBCK@scrollBar@			; `string'
;	COMDAT ??_C@_09LBJLMBCK@scrollBar@
CONST	SEGMENT
??_C@_09LBJLMBCK@scrollBar@ DB 'scrollBar', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@EDDKEFDJ@contentBar@
CONST	SEGMENT
??_C@_0L@EDDKEFDJ@contentBar@ DB 'contentBar', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_08ENPEKDLI@addEntry@
CONST	SEGMENT
??_C@_08ENPEKDLI@addEntry@ DB 'addEntry', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_06BPMFKDCM@topBar@
CONST	SEGMENT
??_C@_06BPMFKDCM@topBar@ DB 'topBar', 00H		; `string'
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1?$ImVector@UCustomDraw@?1??Sequencer@ImSequencer@@YA_NPEAUSequenceInterface@3@PEAHPEA_N11H@Z@@@QEAA@XZ DD imagerel ??1?$ImVector@UCustomDraw@?1??Sequencer@ImSequencer@@YA_NPEAUSequenceInterface@3@PEAHPEA_N11H@Z@@@QEAA@XZ
	DD	imagerel ??1?$ImVector@UCustomDraw@?1??Sequencer@ImSequencer@@YA_NPEAUSequenceInterface@3@PEAHPEA_N11H@Z@@@QEAA@XZ+35
	DD	imagerel $unwind$??1?$ImVector@UCustomDraw@?1??Sequencer@ImSequencer@@YA_NPEAUSequenceInterface@3@PEAHPEA_N11H@Z@@@QEAA@XZ
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??1?$ImVector@UCustomDraw@?1??Sequencer@ImSequencer@@YA_NPEAUSequenceInterface@3@PEAHPEA_N11H@Z@@@QEAA@XZ DB 00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$??1?$ImVector@UCustomDraw@?1??Sequencer@ImSequencer@@YA_NPEAUSequenceInterface@3@PEAHPEA_N11H@Z@@@QEAA@XZ DB 060H
	DD	imagerel $ip2state$??1?$ImVector@UCustomDraw@?1??Sequencer@ImSequencer@@YA_NPEAUSequenceInterface@3@PEAHPEA_N11H@Z@@@QEAA@XZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1?$ImVector@UCustomDraw@?1??Sequencer@ImSequencer@@YA_NPEAUSequenceInterface@3@PEAHPEA_N11H@Z@@@QEAA@XZ DD 019H
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$??1?$ImVector@UCustomDraw@?1??Sequencer@ImSequencer@@YA_NPEAUSequenceInterface@3@PEAHPEA_N11H@Z@@@QEAA@XZ
; Function compile flags: /Ogtpy
; File H:\Paul\switchemulator\Zelda TotK\MapEditorV4\OldVersion\MapEditor\imgui\imgui.h
; File H:\Paul\switchemulator\Zelda TotK\MapEditorV4\OldVersion\MapEditor\imgui\imgui.cpp
; File H:\Paul\switchemulator\Zelda TotK\MapEditorV4\OldVersion\MapEditor\imgui\imgui.h
;	COMDAT ??1?$ImVector@UCustomDraw@?1??Sequencer@ImSequencer@@YA_NPEAUSequenceInterface@3@PEAHPEA_N11H@Z@@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??1?$ImVector@UCustomDraw@?1??Sequencer@ImSequencer@@YA_NPEAUSequenceInterface@3@PEAHPEA_N11H@Z@@@QEAA@XZ PROC ; ImVector<`ImSequencer::Sequencer'::`2'::CustomDraw>::~ImVector<`ImSequencer::Sequencer'::`2'::CustomDraw>, COMDAT

; 1906 :     inline ~ImVector()                                      { if (Data) IM_FREE(Data); } // Important: does not destruct anything

	mov	rcx, QWORD PTR [rcx+8]
	test	rcx, rcx
	je	SHORT $LN8@ImVector
; File H:\Paul\switchemulator\Zelda TotK\MapEditorV4\OldVersion\MapEditor\imgui\imgui.cpp

; 4312 :         if (ImGuiContext* ctx = GImGui)

	mov	rax, QWORD PTR ?GImGui@@3PEAUImGuiContext@@EA ; GImGui
	test	rax, rax
	je	SHORT $LN6@ImVector

; 4313 :             ctx->IO.MetricsActiveAllocations--;

	dec	DWORD PTR [rax+244]
$LN6@ImVector:

; 1159 : static void    FreeWrapper(void* ptr, void* user_data)        { IM_UNUSED(user_data); free(ptr); }

	rex_jmp	QWORD PTR __imp_free
$LN8@ImVector:
; File H:\Paul\switchemulator\Zelda TotK\MapEditorV4\OldVersion\MapEditor\imgui\imgui.h

; 1906 :     inline ~ImVector()                                      { if (Data) IM_FREE(Data); } // Important: does not destruct anything

	ret	0
??1?$ImVector@UCustomDraw@?1??Sequencer@ImSequencer@@YA_NPEAUSequenceInterface@3@PEAHPEA_N11H@Z@@@QEAA@XZ ENDP ; ImVector<`ImSequencer::Sequencer'::`2'::CustomDraw>::~ImVector<`ImSequencer::Sequencer'::`2'::CustomDraw>
_TEXT	ENDS
END
