; Listing generated by Microsoft (R) Optimizing Compiler Version 19.37.32822.0 

include listing.inc

INCLUDELIB OLDNAMES

?sRecastAssertFailFunc@@3P6AXPEBD0H@ZEA DQ 01H DUP (?)	; sRecastAssertFailFunc
_BSS	ENDS
PUBLIC	?rcAssertFailGetCustom@@YAP6AXPEBD0H@ZXZ	; rcAssertFailGetCustom
; Function compile flags: /Ogtpy
; File H:\Paul\switchemulator\Zelda TotK\MapEditorV4\OldVersion\MapEditor\recastnavigation\recast\RecastAssert.cpp
;	COMDAT ?rcAssertFailGetCustom@@YAP6AXPEBD0H@ZXZ
_TEXT	SEGMENT
?rcAssertFailGetCustom@@YAP6AXPEBD0H@ZXZ PROC		; rcAssertFailGetCustom, COMDAT

; 32   : 	return sRecastAssertFailFunc;

	mov	rax, QWORD PTR ?sRecastAssertFailFunc@@3P6AXPEBD0H@ZEA

; 33   : }

	ret	0
?rcAssertFailGetCustom@@YAP6AXPEBD0H@ZXZ ENDP		; rcAssertFailGetCustom
_TEXT	ENDS
END
