#include "TextureFormat.h"

namespace application::file::game::texture
{
    uint32_t TextureFormat::GetFormatBytesPerBlock(Format format) 
    {
        switch (format) 
        {
        case Format::R8_SINT:
        case Format::R8_SNORM:
        case Format::R4G4_UNORM:
        case Format::R8_UINT:
        case Format::R8_UNORM:
            return 1;
        case Format::B5G5R5A1_UNORM:
        case Format::R5G5B5A1_UNORM:
        case Format::R5G5B5_UNORM:
        case Format::B4G4R4A4_UNORM:
        case Format::R8G8_SINT:
        case Format::R8G8_SNORM:
        case Format::R8G8_UINT:
        case Format::R8G8_UNORM:
        case Format::R16_SINT:
        case Format::R16_SNORM:
        case Format::R16_UINT:
        case Format::R16_UNORM:
        case Format::B5G6R5_UNORM:
        case Format::D16_UNORM:
            return 2;
        case Format::R8G8B8A8_SINT:
        case Format::R8G8B8A8_SNORM:
        case Format::R8G8B8A8_UINT:
        case Format::R8G8B8A8_UNORM:
        case Format::R8G8B8A8_UNORM_SRGB:
        case Format::R32G8X24_FLOAT:
        case Format::R8G8_B8G8_UNORM:
        case Format::B8G8R8X8_UNORM:
        case Format::B8G8R8A8_UNORM:
        case Format::B8G8R8A8_UNORM_SRGB:
        case Format::R10G10B10A2_UINT:
        case Format::R10G10B10A2_UNORM:
        case Format::R32_SINT:
        case Format::R32_UINT:
        case Format::R32_FLOAT:
        case Format::R16G16_FLOAT:
        case Format::R16G16_SINT:
        case Format::R16G16_SNORM:
        case Format::R16G16_UINT:
        case Format::R16G16_UNORM:
        case Format::R11G11B10_FLOAT:
        case Format::ETC1_UNORM:
        case Format::ETC1_SRGB:
        case Format::L4:
        case Format::LA4:
        case Format::A4:
        case Format::D24_UNORM_S8_UINT:
        case Format::D32_FLOAT:
        case Format::I4:
        case Format::C4:
        case Format::CMPR:
            return 4;
        case Format::R32G32B32_FLOAT:
        case Format::R16G16B16A16_FLOAT:
        case Format::R16G16B16A16_SINT:
        case Format::R16G16B16A16_SNORM:
        case Format::R32G32_FLOAT:
        case Format::R32G32_SINT:
        case Format::R32G32_UINT:
        case Format::BC1_UNORM:
        case Format::BC1_UNORM_SRGB:
        case Format::BC4_UNORM:
        case Format::BC4_SNORM:
        case Format::ETC1_A4:
        case Format::L8:
        case Format::A8_UNORM:
        case Format::D32_FLOAT_S8X24_UINT:
        case Format::I8:
        case Format::IA4:
        case Format::C8:
            return 8;
        case Format::R32G32B32A32_FLOAT:
        case Format::R32G32B32A32_SINT:
        case Format::R32G32B32A32_UINT:
        case Format::BC2_UNORM:
        case Format::BC2_UNORM_SRGB:
        case Format::BC3_UNORM:
        case Format::BC3_UNORM_SRGB:
        case Format::BC5_UNORM:
        case Format::BC5_SNORM:
        case Format::BC6H_SF16:
        case Format::BC6H_UF16:
        case Format::BC7_UNORM:
        case Format::BC7_UNORM_SRGB:
        case Format::ASTC_4x4_UNORM:
        case Format::ASTC_4x4_SRGB:
        case Format::ASTC_5x4_UNORM:
        case Format::ASTC_5x4_SRGB:
        case Format::ASTC_5x5_UNORM:
        case Format::ASTC_5x5_SRGB:
        case Format::ASTC_6x5_UNORM:
        case Format::ASTC_6x5_SRGB:
        case Format::ASTC_6x6_UNORM:
        case Format::ASTC_6x6_SRGB:
        case Format::ASTC_8x5_UNORM:
        case Format::ASTC_8x5_SRGB:
        case Format::ASTC_8x6_UNORM:
        case Format::ASTC_8x6_SRGB:
        case Format::ASTC_8x8_UNORM:
        case Format::ASTC_8x8_SRGB:
        case Format::ASTC_10x5_UNORM:
        case Format::ASTC_10x5_SRGB:
        case Format::ASTC_10x6_UNORM:
        case Format::ASTC_10x6_SRGB:
        case Format::ASTC_10x8_UNORM:
        case Format::ASTC_10x8_SRGB:
        case Format::ASTC_10x10_UNORM:
        case Format::ASTC_10x10_SRGB:
        case Format::ASTC_12x10_UNORM:
        case Format::ASTC_12x10_SRGB:
        case Format::ASTC_12x12_UNORM:
        case Format::ASTC_12x12_SRGB:
        case Format::HIL08:
        case Format::LA8:
        case Format::IA8:
        case Format::RGB565:
        case Format::RGB5A3:
        case Format::C14X2:
            return 16;
        case Format::RGBA32:
            return 32;
        default:
            return 0;
        }
    }

    uint32_t TextureFormat::GetFormatBlockWidth(Format format) 
    {
        switch (format) 
        {
        case Format::R32G32B32A32_FLOAT:
        case Format::R32G32B32A32_SINT:
        case Format::R32G32B32A32_UINT:
        case Format::R32G32B32_FLOAT:
        case Format::R16G16B16A16_FLOAT:
        case Format::R16G16B16A16_SINT:
        case Format::R16G16B16A16_SNORM:
        case Format::R32G32_FLOAT:
        case Format::R32G32_SINT:
        case Format::R32G32_UINT:
        case Format::R8G8B8A8_SINT:
        case Format::R8G8B8A8_SNORM:
        case Format::R8G8B8A8_UINT:
        case Format::R8G8B8A8_UNORM:
        case Format::R8G8B8A8_UNORM_SRGB:
        case Format::R32G8X24_FLOAT:
        case Format::R8G8_B8G8_UNORM:
        case Format::B8G8R8X8_UNORM:
        case Format::B5G5R5A1_UNORM:
        case Format::R5G5B5A1_UNORM:
        case Format::B8G8R8A8_UNORM:
        case Format::B8G8R8A8_UNORM_SRGB:
        case Format::R5G5B5_UNORM:
        case Format::R10G10B10A2_UINT:
        case Format::R10G10B10A2_UNORM:
        case Format::R32_SINT:
        case Format::R32_UINT:
        case Format::R32_FLOAT:
        case Format::B4G4R4A4_UNORM:
        case Format::R16G16_FLOAT:
        case Format::R16G16_SINT:
        case Format::R16G16_SNORM:
        case Format::R16G16_UINT:
        case Format::R16G16_UNORM:
        case Format::R8G8_SINT:
        case Format::R8G8_SNORM:
        case Format::R8G8_UINT:
        case Format::R8G8_UNORM:
        case Format::R16_SINT:
        case Format::R16_SNORM:
        case Format::R16_UINT:
        case Format::R16_UNORM:
        case Format::R8_SINT:
        case Format::R8_SNORM:
        case Format::R4G4_UNORM:
        case Format::R8_UINT:
        case Format::R8_UNORM:
        case Format::R11G11B10_FLOAT:
        case Format::B5G6R5_UNORM:
        case Format::ETC1_UNORM:
        case Format::ETC1_SRGB:
        case Format::ETC1_A4:
        case Format::HIL08:
        case Format::L4:
        case Format::L8:
        case Format::LA8:
        case Format::A4:
        case Format::A8_UNORM:
        case Format::D16_UNORM:
        case Format::D24_UNORM_S8_UINT:
        case Format::D32_FLOAT:
        case Format::D32_FLOAT_S8X24_UINT:
            return 1;
        case Format::BC1_UNORM:
        case Format::BC1_UNORM_SRGB:
        case Format::BC2_UNORM:
        case Format::BC2_UNORM_SRGB:
        case Format::BC3_UNORM:
        case Format::BC3_UNORM_SRGB:
        case Format::BC4_UNORM:
        case Format::BC4_SNORM:
        case Format::BC5_UNORM:
        case Format::BC5_SNORM:
        case Format::BC6H_SF16:
        case Format::BC6H_UF16:
        case Format::BC7_UNORM:
        case Format::BC7_UNORM_SRGB:
        case Format::ASTC_4x4_UNORM:
        case Format::ASTC_4x4_SRGB:
        case Format::IA8:
        case Format::RGB565:
        case Format::RGB5A3:
        case Format::RGBA32:
        case Format::C14X2:
            return 4;
        case Format::ASTC_5x4_UNORM:
        case Format::ASTC_5x4_SRGB:
        case Format::ASTC_5x5_UNORM:
        case Format::ASTC_5x5_SRGB:
            return 5;
        case Format::ASTC_6x5_UNORM:
        case Format::ASTC_6x5_SRGB:
        case Format::ASTC_6x6_UNORM:
        case Format::ASTC_6x6_SRGB:
            return 6;
        case Format::ASTC_8x5_UNORM:
        case Format::ASTC_8x5_SRGB:
        case Format::ASTC_8x6_UNORM:
        case Format::ASTC_8x6_SRGB:
        case Format::ASTC_8x8_UNORM:
        case Format::ASTC_8x8_SRGB:
        case Format::I4:
        case Format::I8:
        case Format::IA4:
        case Format::C4:
        case Format::C8:
        case Format::CMPR:
            return 8;
        case Format::ASTC_10x5_UNORM:
        case Format::ASTC_10x5_SRGB:
        case Format::ASTC_10x6_UNORM:
        case Format::ASTC_10x6_SRGB:
        case Format::ASTC_10x8_UNORM:
        case Format::ASTC_10x8_SRGB:
        case Format::ASTC_10x10_UNORM:
        case Format::ASTC_10x10_SRGB:
            return 10;
        case Format::ASTC_12x10_UNORM:
        case Format::ASTC_12x10_SRGB:
        case Format::ASTC_12x12_UNORM:
        case Format::ASTC_12x12_SRGB:
            return 12;
        default:
            return 0;
        }
    }

    uint32_t TextureFormat::GetFormatBlockHeight(Format format) 
    {
        switch (format) 
        {
        case Format::R32G32B32A32_FLOAT:
        case Format::R32G32B32A32_SINT:
        case Format::R32G32B32A32_UINT:
        case Format::R32G32B32_FLOAT:
        case Format::R16G16B16A16_FLOAT:
        case Format::R16G16B16A16_SINT:
        case Format::R16G16B16A16_SNORM:
        case Format::R32G32_FLOAT:
        case Format::R32G32_SINT:
        case Format::R32G32_UINT:
        case Format::R8G8B8A8_SINT:
        case Format::R8G8B8A8_SNORM:
        case Format::R8G8B8A8_UINT:
        case Format::R8G8B8A8_UNORM:
        case Format::R8G8B8A8_UNORM_SRGB:
        case Format::R32G8X24_FLOAT:
        case Format::R8G8_B8G8_UNORM:
        case Format::B8G8R8X8_UNORM:
        case Format::B5G5R5A1_UNORM:
        case Format::R5G5B5A1_UNORM:
        case Format::B8G8R8A8_UNORM:
        case Format::B8G8R8A8_UNORM_SRGB:
        case Format::R5G5B5_UNORM:
        case Format::R10G10B10A2_UINT:
        case Format::R10G10B10A2_UNORM:
        case Format::R32_SINT:
        case Format::R32_UINT:
        case Format::R32_FLOAT:
        case Format::B4G4R4A4_UNORM:
        case Format::R16G16_FLOAT:
        case Format::R16G16_SINT:
        case Format::R16G16_SNORM:
        case Format::R16G16_UINT:
        case Format::R16G16_UNORM:
        case Format::R8G8_SINT:
        case Format::R8G8_SNORM:
        case Format::R8G8_UINT:
        case Format::R8G8_UNORM:
        case Format::R16_SINT:
        case Format::R16_SNORM:
        case Format::R16_UINT:
        case Format::R16_UNORM:
        case Format::R8_SINT:
        case Format::R8_SNORM:
        case Format::R4G4_UNORM:
        case Format::R8_UINT:
        case Format::R8_UNORM:
        case Format::R11G11B10_FLOAT:
        case Format::B5G6R5_UNORM:
        case Format::ETC1_UNORM:
        case Format::ETC1_SRGB:
        case Format::ETC1_A4:
        case Format::HIL08:
        case Format::L4:
        case Format::L8:
        case Format::LA8:
        case Format::A4:
        case Format::A8_UNORM:
        case Format::D16_UNORM:
        case Format::D24_UNORM_S8_UINT:
        case Format::D32_FLOAT:
        case Format::D32_FLOAT_S8X24_UINT:
            return 1;
        case Format::BC1_UNORM:
        case Format::BC1_UNORM_SRGB:
        case Format::BC2_UNORM:
        case Format::BC2_UNORM_SRGB:
        case Format::BC3_UNORM:
        case Format::BC3_UNORM_SRGB:
        case Format::BC4_UNORM:
        case Format::BC4_SNORM:
        case Format::BC5_UNORM:
        case Format::BC5_SNORM:
        case Format::BC6H_SF16:
        case Format::BC6H_UF16:
        case Format::BC7_UNORM:
        case Format::BC7_UNORM_SRGB:
        case Format::ASTC_4x4_UNORM:
        case Format::ASTC_4x4_SRGB:
        case Format::ASTC_5x4_UNORM:
        case Format::ASTC_5x4_SRGB:
        case Format::I8:
        case Format::IA4:
        case Format::IA8:
        case Format::RGB565:
        case Format::RGB5A3:
        case Format::RGBA32:
        case Format::C8:
        case Format::C14X2:
            return 4;
        case Format::ASTC_5x5_UNORM:
        case Format::ASTC_5x5_SRGB:
        case Format::ASTC_6x5_UNORM:
        case Format::ASTC_6x5_SRGB:
        case Format::ASTC_8x5_UNORM:
        case Format::ASTC_8x5_SRGB:
        case Format::ASTC_10x5_UNORM:
        case Format::ASTC_10x5_SRGB:
            return 5;
        case Format::ASTC_6x6_UNORM:
        case Format::ASTC_6x6_SRGB:
        case Format::ASTC_8x6_UNORM:
        case Format::ASTC_8x6_SRGB:
        case Format::ASTC_10x6_UNORM:
        case Format::ASTC_10x6_SRGB:
            return 6;
        case Format::ASTC_8x8_UNORM:
        case Format::ASTC_8x8_SRGB:
        case Format::ASTC_10x8_UNORM:
        case Format::ASTC_10x8_SRGB:
        case Format::I4:
        case Format::C4:
        case Format::CMPR:
            return 8;
        case Format::ASTC_10x10_UNORM:
        case Format::ASTC_10x10_SRGB:
        case Format::ASTC_12x10_UNORM:
        case Format::ASTC_12x10_SRGB:
            return 10;
        case Format::ASTC_12x12_UNORM:
        case Format::ASTC_12x12_SRGB:
            return 12;
        default:
            return 0;
        }
    }

    uint32_t TextureFormat::GetFormatBlockDepth(Format format) 
    {
        switch (format) 
        {
        case Format::R32G32B32A32_FLOAT:
        case Format::R32G32B32A32_SINT:
        case Format::R32G32B32A32_UINT:
        case Format::R32G32B32_FLOAT:
        case Format::R16G16B16A16_FLOAT:
        case Format::R16G16B16A16_SINT:
        case Format::R16G16B16A16_SNORM:
        case Format::R32G32_FLOAT:
        case Format::R32G32_SINT:
        case Format::R32G32_UINT:
        case Format::R8G8B8A8_SINT:
        case Format::R8G8B8A8_SNORM:
        case Format::R8G8B8A8_UINT:
        case Format::R8G8B8A8_UNORM:
        case Format::R8G8B8A8_UNORM_SRGB:
        case Format::R32G8X24_FLOAT:
        case Format::R8G8_B8G8_UNORM:
        case Format::B8G8R8X8_UNORM:
        case Format::B5G5R5A1_UNORM:
        case Format::R5G5B5A1_UNORM:
        case Format::B8G8R8A8_UNORM:
        case Format::B8G8R8A8_UNORM_SRGB:
        case Format::R5G5B5_UNORM:
        case Format::R10G10B10A2_UINT:
        case Format::R10G10B10A2_UNORM:
        case Format::R32_SINT:
        case Format::R32_UINT:
        case Format::R32_FLOAT:
        case Format::B4G4R4A4_UNORM:
        case Format::R16G16_FLOAT:
        case Format::R16G16_SINT:
        case Format::R16G16_SNORM:
        case Format::R16G16_UINT:
        case Format::R16G16_UNORM:
        case Format::R8G8_SINT:
        case Format::R8G8_SNORM:
        case Format::R8G8_UINT:
        case Format::R8G8_UNORM:
        case Format::R16_SINT:
        case Format::R16_SNORM:
        case Format::R16_UINT:
        case Format::R16_UNORM:
        case Format::R8_SINT:
        case Format::R8_SNORM:
        case Format::R4G4_UNORM:
        case Format::R8_UINT:
        case Format::R8_UNORM:
        case Format::R11G11B10_FLOAT:
        case Format::B5G6R5_UNORM:
        case Format::ETC1_UNORM:
        case Format::ETC1_SRGB:
        case Format::ETC1_A4:
        case Format::HIL08:
        case Format::L4:
        case Format::L8:
        case Format::LA8:
        case Format::A4:
        case Format::A8_UNORM:
        case Format::D16_UNORM:
        case Format::D24_UNORM_S8_UINT:
        case Format::D32_FLOAT:
        case Format::D32_FLOAT_S8X24_UINT:
        case Format::BC1_UNORM:
        case Format::BC1_UNORM_SRGB:
        case Format::BC2_UNORM:
        case Format::BC2_UNORM_SRGB:
        case Format::BC3_UNORM:
        case Format::BC3_UNORM_SRGB:
        case Format::BC4_UNORM:
        case Format::BC4_SNORM:
        case Format::BC5_UNORM:
        case Format::BC5_SNORM:
        case Format::BC6H_SF16:
        case Format::BC6H_UF16:
        case Format::BC7_UNORM:
        case Format::BC7_UNORM_SRGB:
        case Format::ASTC_4x4_UNORM:
        case Format::ASTC_4x4_SRGB:
        case Format::IA8:
        case Format::RGB565:
        case Format::RGB5A3:
        case Format::RGBA32:
        case Format::C14X2:
        case Format::ASTC_5x4_UNORM:
        case Format::ASTC_5x4_SRGB:
        case Format::ASTC_5x5_UNORM:
        case Format::ASTC_5x5_SRGB:
        case Format::ASTC_6x5_UNORM:
        case Format::ASTC_6x5_SRGB:
        case Format::ASTC_6x6_UNORM:
        case Format::ASTC_6x6_SRGB:
        case Format::ASTC_8x5_UNORM:
        case Format::ASTC_8x5_SRGB:
        case Format::ASTC_8x6_UNORM:
        case Format::ASTC_8x6_SRGB:
        case Format::ASTC_8x8_UNORM:
        case Format::ASTC_8x8_SRGB:
        case Format::I4:
        case Format::I8:
        case Format::IA4:
        case Format::C4:
        case Format::C8:
        case Format::CMPR:
        case Format::ASTC_10x5_UNORM:
        case Format::ASTC_10x5_SRGB:
        case Format::ASTC_10x6_UNORM:
        case Format::ASTC_10x6_SRGB:
        case Format::ASTC_10x8_UNORM:
        case Format::ASTC_10x8_SRGB:
        case Format::ASTC_10x10_UNORM:
        case Format::ASTC_10x10_SRGB:
        case Format::ASTC_12x10_UNORM:
        case Format::ASTC_12x10_SRGB:
        case Format::ASTC_12x12_UNORM:
        case Format::ASTC_12x12_SRGB:
            return 1;
        default:
            return 0;
        }
    }
}